data:
    modality: "pose"
    train_pipeline:
        dataset:
            _target_: openhands.datasets.isolated.ASLLVDDataset
            split_file: "data/ASLLVD/splitted/train_label.json"           
            root_dir: "data/ASLLVD/PKL_POSES"
            class_mappings_file_path: "data/ASLLVD/segmented/label_name.txt"
            splits: "train"
            modality: "pose"
            seq_len: 10
            num_seq: 6

        transforms:
            - PoseSelect:
                preset: mediapipe_holistic_minimal_27
            - CenterAndScaleNormalize:
                reference_points_preset: shoulder_mediapipe_holistic_minimal_27
            - ShearTransform:
                shear_std: 0.1
            - RotatationTransform:
                rotation_std: 0.1

        dataloader:
            _target_: torch.utils.data.DataLoader
            batch_size: 32
            shuffle: true
            num_workers: 6
            pin_memory: true
            # drop_last: true

    valid_pipeline:
        dataset:
            _target_: openhands.datasets.isolated.ASLLVDDataset
            split_file: "data/ASLLVD/splitted/test_label.json"
            root_dir: "data/ASLLVD/PKL_POSES"
            class_mappings_file_path: "data/ASLLVD/segmented/label_name.txt"
            splits: "test"
            modality: "pose"
            seq_len: 10
            num_seq: 6

        transforms:
            - PoseSelect:
                preset: mediapipe_holistic_minimal_27
            - CenterAndScaleNormalize:
                reference_points_preset: shoulder_mediapipe_holistic_minimal_27

        dataloader:
            _target_: torch.utils.data.DataLoader
            batch_size: 32
            shuffle: false
            num_workers: 8
            pin_memory: true
            drop_last: false

model:
    pretrained:
      type: dpc
      load_from:
        cfg_file: /home/iitm/OpenHands/examples/ssl/pretrain_dpc_decoupled_gcn.yaml
        ckpt: /home/iitm/pretrainedCheckpoint/epoch=698-step=1098827.ckpt

optim:
    loss: 'CrossEntropyLoss'
    optimizer:
        name: Adam
        params:
            lr: 1e-4

    scheduler:
        name: CosineAnnealingLR
        params:
            last_epoch: -1
            T_max: 20

trainer:
    gpus: [1]
    max_epochs: 1000
    # resume_from_checkpoint: /home/gokulnc/openhands/openhands_experiments/INCLUDE/BERT-Fine-tuned-full/epoch=1493-step=82169.ckpt

exp_manager:
    create_tensorboard_logger: true
    create_wandb_logger: true
    wandb_logger_kwargs:
        name: "finetuneWithDecouplingGCN_lr_4_epoch698"
        project: "asllvd_With_Pretraining"

    create_checkpoint_callback: true
    checkpoint_callback_params:
        monitor: "val_acc"
        mode: "max"
        save_top_k: 3
        dirpath: "experiments/asllvd/finetuneWithDecouplingGCN_lr_4_epoch698/"

    early_stopping_callback: true
    early_stopping_params:
        monitor: "val_acc"
        patience: 200
        verbose: true
        mode: "max"
