data:
    modality: "pose"
    train_pipeline:
        dataset:
            _target_: openhands.datasets.isolated.RWTH_Phoenix_Signer03_Dataset
            split_file: "/home/iitm/OpenHands/openhands/datasets/assets/rwth_phoenix_weather_signer03_cutout_metadata/RWTH-PHOENIX-Weather-Signer03-cutout.train.corpus"           
            root_dir: "rwth-phoenix-weather-signer03-cutout/RWTH-PHOENIX-Weather-Signer03-cutout/TRAIN_POSES"
            class_mappings_file_path: "/home/iitm/OpenHands/openhands/datasets/assets/rwth_phoenix_weather_signer03_cutout_metadata/RWTH-PHOENIX-Weather-Signer03-cutout.data.corpus"
            splits: "train"
            modality: "pose"
            seq_len: 10
            num_seq: 6

        transforms:
            - PoseSelect:
                preset: mediapipe_holistic_minimal_27
            - CenterAndScaleNormalize:
                reference_points_preset: shoulder_mediapipe_holistic_minimal_27
            - ShearTransform:
                shear_std: 0.1
            - RotatationTransform:
                rotation_std: 0.1

        dataloader:
            _target_: torch.utils.data.DataLoader
            batch_size: 32
            shuffle: true
            num_workers: 6
            pin_memory: true
            # drop_last: true

    valid_pipeline:
        dataset:
            _target_: openhands.datasets.isolated.RWTH_Phoenix_Signer03_Dataset
            split_file: "/home/iitm/OpenHands/openhands/datasets/assets/rwth_phoenix_weather_signer03_cutout_metadata/RWTH-PHOENIX-Weather-Signer03-cutout.test.corpus"
            root_dir: "rwth-phoenix-weather-signer03-cutout/RWTH-PHOENIX-Weather-Signer03-cutout/TEST_POSES"
            class_mappings_file_path: "/home/iitm/OpenHands/openhands/datasets/assets/rwth_phoenix_weather_signer03_cutout_metadata/RWTH-PHOENIX-Weather-Signer03-cutout.data.corpus"
            splits: "test"
            modality: "pose"
            seq_len: 10
            num_seq: 6

        transforms:
            - PoseSelect:
                preset: mediapipe_holistic_minimal_27
            - CenterAndScaleNormalize:
                reference_points_preset: shoulder_mediapipe_holistic_minimal_27

        dataloader:
            _target_: torch.utils.data.DataLoader
            batch_size: 32
            shuffle: false
            num_workers: 8
            pin_memory: true
            drop_last: false

model:
    pretrained:
      type: dpc
      load_from:
        cfg_file: /home/iitm/OpenHands/examples/ssl/pretrain_dpc_decoupled_gcn.yaml
        ckpt: /home/iitm/pretrainedCheckpoint/epoch=698-step=1098827.ckpt

optim:
    loss: 'CrossEntropyLoss'
    optimizer:
        name: Adam
        params:
            lr: 1e-5

    scheduler:
        name: CosineAnnealingLR
        params:
            last_epoch: -1
            T_max: 20

trainer:
    gpus: [1]
    max_epochs: 1000
    # resume_from_checkpoint: /home/gokulnc/openhands/openhands_experiments/INCLUDE/BERT-Fine-tuned-full/epoch=1493-step=82169.ckpt

exp_manager:
    create_tensorboard_logger: true
    create_wandb_logger: true
    wandb_logger_kwargs:
        name: "finetuneWithdecoupledgcn_lr5_epoch698"
        project: "rwth_With_Pretraining"

    create_checkpoint_callback: true
    checkpoint_callback_params:
        monitor: "val_acc"
        mode: "max"
        save_top_k: 3
        dirpath: "experiments/rwth/finetuneWithdecoupledgcn_lr5_epoch698/"

    early_stopping_callback: true
    early_stopping_params:
        monitor: "val_acc"
        patience: 200
        verbose: true
        mode: "max"
