pretrained: "/home/gokulnc/SLR/experiments/multilingual/st_gcn/epoch=132-step=170505.ckpt"

data:
    modality: "pose"
    train_pipeline:
        dataset:
            _target_: openhands.datasets.isolated.ConcatDataset
            datasets:
                # - AUTSLDataset:
                #     split_file: "openhands/datasets/assets/autsl_metadata/AUTSL/train_labels.csv"
                #     root_dir: "/home/prem/data-disk/datasets/AUTSL/poses_pickle/train_poses/new_train_poses"
                #     class_mappings_file_path: "openhands/datasets/assets/autsl_metadata/AUTSL/SignList_ClassId_TR_EN.csv"
                # CSLDataset:
                #     split_file: "openhands/datasets/assets/csl_metadata/split.train.csv"
                #     root_dir: "/home/gokulnc/data-disk/datasets/Chinese/CSL/word/pose_mediapipe/"
                #     class_mappings_file_path: "openhands/datasets/assets/csl_metadata/CSL/gloss_label.txt"
                # DeviSignDataset:
                #     split_file: "openhands/datasets/assets/devisign_metadata/split.train.csv"
                #     root_dir: "/home/gokulnc/data-disk/datasets/Chinese/DEVISIGN/poses_pickled"
                #     class_mappings_file_path: "openhands/datasets/assets/devisign_metadata/Documents/4414To2000(DEVISIGN_L)_ID&Meaning.txt"
                GSLDataset:
                    split_file: "openhands/datasets/assets/gsl_metadata/GSL_split/GSL_isolated/train_greek_iso.csv"
                    root_dir: "/home/gokulnc/data-disk/datasets/Greek/Greek_isolated/GSL_pose"
                    class_mappings_file_path: "openhands/datasets/assets/gsl_metadata/GSL_split/GSL_isolated/iso_classes.csv"
                    # only_metadata: True
                INCLUDEDataset:
                    split_file: "openhands/datasets/assets/include_metadata/Train_Test_Split/train_include.csv"
                    root_dir: "/home/gokulnc/data-disk/datasets/Indian/INCLUDE/Pose_Signs"
                    only_metadata: True
                LSA64Dataset:
                    root_dir: "/home/gokulnc/data-disk/datasets/Argentinian/lsa64/pose_all_cut/"
                    class_mappings_file_path: "openhands/datasets/assets/lsa64_metadata/LSA64_Cut/lsa64_signs.md"
                    only_metadata: True
                # WLASLDataset:
                #     split_file: "openhands/datasets/assets/wlasl_metadata/splits/asl2000.json"
                #     root_dir: "/home/gokulnc/data-disk/datasets/American/WLASL2000/poses_pickle"
            modality: "pose"
            splits: "train"

        transforms:
            - PoseSelect:
                preset: mediapipe_holistic_minimal_27
            - CenterAndScaleNormalize:
                reference_points_preset: shoulder_mediapipe_holistic_minimal_27
            - ShearTransform:
                shear_std: 0.1
            - RotatationTransform:
                rotation_std: 0.1
            - PrependLangCodeOHE:
                lang_codes:
                    - aed # Argentinian
                    - ase # American
                    - csl # Chinese
                    - gsg # German
                    - gss # Greek
                    - ins # Indian
                    - tsm # Turkish

        dataloader:
            _target_: torch.utils.data.DataLoader
            batch_size: 32
            shuffle: true
            num_workers: 3
            pin_memory: true
            drop_last: false

    valid_pipeline:
        dataset:
            _target_: openhands.datasets.isolated.ConcatDataset
            datasets:
                # - AUTSLDataset:
                #     split_file: "openhands/datasets/assets/autsl_metadata/AUTSL/validation_labels.csv"
                #     root_dir: "/home/prem/data-disk/datasets/AUTSL/poses_pickle/val_poses/new_val_poses/"
                #     class_mappings_file_path: "openhands/datasets/assets/autsl_metadata/AUTSL/SignList_ClassId_TR_EN.csv"
                # CSLDataset:
                #     split_file: "openhands/datasets/assets/csl_metadata/split.test.csv"
                #     root_dir: "/home/gokulnc/data-disk/datasets/Chinese/CSL/word/pose_mediapipe/"
                #     class_mappings_file_path: "openhands/datasets/assets/csl_metadata/CSL/gloss_label.txt"
                # DeviSignDataset:
                #     split_file: "openhands/datasets/assets/devisign_metadata/split.test.csv"
                #     root_dir: "/home/gokulnc/data-disk/datasets/Chinese/DEVISIGN/poses_pickled"
                #     class_mappings_file_path: "openhands/datasets/assets/devisign_metadata/Documents/4414To2000(DEVISIGN_L)_ID&Meaning.txt"
                GSLDataset:
                    split_file: "openhands/datasets/assets/gsl_metadata/GSL_split/GSL_isolated/test_greek_iso.csv"
                    root_dir: "/home/gokulnc/data-disk/datasets/Greek/Greek_isolated/GSL_pose"
                    class_mappings_file_path: "openhands/datasets/assets/gsl_metadata/GSL_split/GSL_isolated/iso_classes.csv"
                    # only_metadata: True
                INCLUDEDataset:
                    split_file: "openhands/datasets/assets/include_metadata/Train_Test_Split/test_include.csv"
                    root_dir: "/home/gokulnc/data-disk/datasets/Indian/INCLUDE/Pose_Signs"
                    only_metadata: True
                LSA64Dataset:
                    root_dir: "/home/gokulnc/data-disk/datasets/Argentinian/lsa64/pose_all_cut/"
                    class_mappings_file_path: "openhands/datasets/assets/lsa64_metadata/LSA64_Cut/lsa64_signs.md"
                    only_metadata: True
                # WLASLDataset:
                #     split_file: "openhands/datasets/assets/wlasl_metadata/splits/asl2000.json"
                #     root_dir: "/home/gokulnc/data-disk/datasets/American/WLASL2000/poses_pickle"
            modality: "pose"
            splits: "test"

        transforms:
            - PoseSelect:
                preset: mediapipe_holistic_minimal_27
            - CenterAndScaleNormalize:
                reference_points_preset: shoulder_mediapipe_holistic_minimal_27
            - PrependLangCodeOHE:
                lang_codes:
                    - aed # Argentinian
                    - ase # American
                    - csl # Chinese
                    - gsg # German
                    - gss # Greek
                    - ins # Indian
                    - tsm # Turkish

        dataloader:
            _target_: torch.utils.data.DataLoader
            batch_size: 128
            shuffle: false
            num_workers: 3
            pin_memory: true
            drop_last: false

    test_pipeline:
        dataset:
            _target_: openhands.datasets.isolated.ConcatDataset
            datasets:
                # - AUTSLDataset:
                #     split_file: "openhands/datasets/assets/autsl_metadata/AUTSL/validation_labels.csv"
                #     root_dir: "/home/prem/data-disk/datasets/AUTSL/poses_pickle/val_poses/new_val_poses/"
                #     class_mappings_file_path: "openhands/datasets/assets/autsl_metadata/AUTSL/SignList_ClassId_TR_EN.csv"
                # CSLDataset:
                #     split_file: "openhands/datasets/assets/csl_metadata/split.test.csv"
                #     root_dir: "/home/gokulnc/data-disk/datasets/Chinese/CSL/word/pose_mediapipe/"
                #     class_mappings_file_path: "openhands/datasets/assets/csl_metadata/CSL/gloss_label.txt"
                # DeviSignDataset:
                #     split_file: "openhands/datasets/assets/devisign_metadata/split.test.csv"
                #     root_dir: "/home/gokulnc/data-disk/datasets/Chinese/DEVISIGN/poses_pickled"
                #     class_mappings_file_path: "openhands/datasets/assets/devisign_metadata/Documents/4414To2000(DEVISIGN_L)_ID&Meaning.txt"
                GSLDataset:
                    split_file: "openhands/datasets/assets/gsl_metadata/GSL_split/GSL_isolated/test_greek_iso.csv"
                    root_dir: "/home/gokulnc/data-disk/datasets/Greek/Greek_isolated/GSL_pose"
                    class_mappings_file_path: "openhands/datasets/assets/gsl_metadata/GSL_split/GSL_isolated/iso_classes.csv"
                    # only_metadata: True
                INCLUDEDataset:
                    split_file: "openhands/datasets/assets/include_metadata/Train_Test_Split/test_include.csv"
                    root_dir: "/home/gokulnc/data-disk/datasets/Indian/INCLUDE/Pose_Signs"
                    only_metadata: True
                LSA64Dataset:
                    root_dir: "/home/gokulnc/data-disk/datasets/Argentinian/lsa64/pose_all_cut/"
                    class_mappings_file_path: "openhands/datasets/assets/lsa64_metadata/LSA64_Cut/lsa64_signs.md"
                    only_metadata: True
                # WLASLDataset:
                #     split_file: "openhands/datasets/assets/wlasl_metadata/splits/asl2000.json"
                #     root_dir: "/home/gokulnc/data-disk/datasets/American/WLASL2000/poses_pickle"
            modality: "pose"
            splits: "test"
            inference_mode: false

        transforms:
            - PoseSelect:
                preset: mediapipe_holistic_minimal_27
            - CenterAndScaleNormalize:
                reference_points_preset: shoulder_mediapipe_holistic_minimal_27
            - PrependLangCodeOHE:
                lang_codes:
                    - aed # Argentinian
                    - ase # American
                    - csl # Chinese
                    - gsg # German
                    - gss # Greek
                    - ins # Indian
                    - tsm # Turkish

        dataloader:
            _target_: torch.utils.data.DataLoader
            batch_size: 128
            shuffle: false
            num_workers: 3
            pin_memory: true
            drop_last: false

model:
    encoder:
        type: st-gcn
        params:
            graph_args:
                num_nodes: 27
                center: 0
                inward_edges:
                    [
                        [2, 0],
                        [1, 0],
                        [0, 3],
                        [0, 4],
                        [3, 5],
                        [4, 6],
                        [5, 7],
                        [6, 17],
                        [7, 8],
                        [7, 9],
                        [9, 10],
                        [7, 11],
                        [11, 12],
                        [7, 13],
                        [13, 14],
                        [7, 15],
                        [15, 16],
                        [17, 18],
                        [17, 19],
                        [19, 20],
                        [17, 21],
                        [21, 22],
                        [17, 23],
                        [23, 24],
                        [17, 25],
                        [25, 26],
                    ]
            edge_importance_weighting: true

    decoder:
        type: fc
        params:
            dropout_ratio: 0.2

optim:
    loss: "CrossEntropyLoss"
    optimizer:
        name: Adam
        params:
            lr: 4e-5

    scheduler:
        name: CosineAnnealingLR
        params:
            last_epoch: -1
            T_max: 10

trainer:
    gpus: 1
    max_epochs: 2000
    # resume_from_checkpoint: "/home/gokulnc/SLR/experiments/multilingual/st_gcn/epoch=132-step=170505.ckpt"

exp_manager:
    create_tensorboard_logger: true
    create_wandb_logger: false
    wandb_logger_kwargs:
        name: null
        project: null

    create_checkpoint_callback: true
    checkpoint_callback_params:
        monitor: "val_acc"
        mode: "max"
        save_top_k: 3
        dirpath: "experiments/multilingual/original_vocab/st_gcn/gsl/"

    early_stopping_callback: true
    early_stopping_params:
        monitor: "val_acc"
        patience: 100
        verbose: true
        mode: "max"
