name: &name "x3d_s_fc"
resume_from: "/home/prem/data-disk/SLR/outputs/2021-06-13/11-47-15/x3d_s_fc/0/checkpoints/epoch=0-step=9.ckpt"

data:
    train_pipeline:
        dataset:
            _target_: slr.datasets.isolated.AUTSLDataset
            split_file: "/home/prem/data-disk/datasets/AUTSL/small_train_labels.csv"
            root_dir: "/home/prem/data-disk/datasets/AUTSL/train"
            resize_dims: (128,128)
            splits: "train"
            transforms: "default"
            modality: "rgb"
            class_mappings_file_path: "/home/prem/data-disk/datasets/AUTSL/SignList_ClassId_TR_EN.csv"

        transforms:
            albumentations:
                - ShiftScaleRotate:
                    shift_limit: 0.05
                    scale_limit: 0.05
                    rotate_limit: 15
                    p: 0.5
            video:
                - NumpyToTensor:
                - THWC2TCHW:
                - RandomTemporalSubsample:
                    num_samples: 16
                - TCHW2CTHW:

            normalization:
                mean: [0.4914, 0.4822, 0.4465]
                std: [0.247, 0.243, 0.261]
        
        dataloader:
            _target_: torch.utils.data.DataLoader
            batch_size: 2
            shuffle: true
            num_workers: 8
            pin_memory: true
            drop_last: true

    valid_pipeline:
        dataset:
            _target_: slr.datasets.isolated.AUTSLDataset
            split_file: "/home/prem/data-disk/datasets/AUTSL/small_train_labels.csv"
            root_dir: "/home/prem/data-disk/datasets/AUTSL/train"
            resize_dims: (128,128)
            splits: "train"
            transforms: "default"
            modality: "rgb"
            class_mappings_file_path: "/home/prem/data-disk/datasets/AUTSL/SignList_ClassId_TR_EN.csv"
    
        transforms:
            albumentations:
                - ShiftScaleRotate:
                    shift_limit: 0.05
                    scale_limit: 0.05
                    rotate_limit: 15
                    p: 0.5
            video:
                - NumpyToTensor:
                - THWC2TCHW:
                - RandomTemporalSubsample:
                    num_samples: 16
                - TCHW2CTHW:

            normalization:
                mean: [0.4914, 0.4822, 0.4465]
                std: [0.247, 0.243, 0.261]
    
        dataloader:
            _target_: torch.utils.data.DataLoader
            batch_size: 2
            shuffle: true
            num_workers: 8
            pin_memory: true
            drop_last: true

model:
    encoder:
        type: cnn3d
        params:
            backbone: x3d_s
            pretrained: true
    decoder:
        type: fc
        params:
            dropout_ratio: 0.2

optim:
    optimizer:
        name: Adam
        params:
            lr: 0.05
            betas: [0.8, 0.25]
            weight_decay: 0.001
    scheduler:
        name: CosineAnnealingLR
        params:
            last_epoch: -1
            T_max: 10

trainer:
    max_epochs: 1
    gpus: 1

exp_manager:
    exp_dir: "./slr_experiments"
    name: *name
    create_tensorboard_logger: true
    create_wandb_logger: false
    wandb_logger_kwargs:
        name: null
        project: null
    
    create_checkpoint_callback: true
    checkpoint_callback_params:
        monitor: "val_acc"
        mode: "min"
        save_top_k: 3