data:
    modality: "pose"
    train_pipeline:
        dataset:
            _target_: openhands.datasets.isolated.bhosporus22k.Bhosporus22kDataset
            class_mappings_file_path: "/datadrive/BosphorusSign22k/BosphorusSign22k.csv"
            root_dir: "/datadrive/BosphorusSign22k/PKL_POSES"
            split_file: "/datadrive/BosphorusSign22k/BosphorusSign22k.csv"
            splits: "train"
            modality: "pose"

        transforms:
            - PoseSelect:
                preset: mediapipe_holistic_minimal_27
            # - PoseTemporalSubsample:
            #       num_frames: 32
            # - RandomMove:
            - CenterAndScaleNormalize:
                reference_points_preset: shoulder_mediapipe_holistic_minimal_27
                scale_factor: 1
            - ShearTransform:
                shear_std: 0.1
            - RotatationTransform:
                rotation_std: 0.1
            # - ScaleTransform:
            #     scale_std: 0.2

        dataloader:
            _target_: torch.utils.data.DataLoader
            batch_size: 32
            shuffle: true
            num_workers: 1
            pin_memory: true
            drop_last: true

    valid_pipeline:
        dataset:
            _target_: openhands.datasets.isolated.bhosporus22k.Bhosporus22kDataset
            class_mappings_file_path: "/datadrive/BosphorusSign22k/BosphorusSign22k.csv"
            root_dir: "/datadrive/BosphorusSign22k/PKL_POSES"
            split_file: "/datadrive/BosphorusSign22k/BosphorusSign22k.csv"
            splits: "val"
            modality: "pose"

        transforms:
            - PoseSelect:
                preset: mediapipe_holistic_minimal_27
            # - PoseTemporalSubsample:
            #       num_frames: 32
            - CenterAndScaleNormalize:
                reference_points_preset: shoulder_mediapipe_holistic_minimal_27
                scale_factor: 1

        dataloader:
            _target_: torch.utils.data.DataLoader
            batch_size: 64
            shuffle: false
            num_workers: 1
            pin_memory: true
            drop_last: false

model:
    encoder:
        type: st-gcn
        params:
            graph_args:
                num_nodes: 27
                center: 0
                inward_edges:
                    [
                        [2, 0],
                        [1, 0],
                        [0, 3],
                        [0, 4],
                        [3, 5],
                        [4, 6],
                        [5, 7],
                        [6, 17],
                        [7, 8],
                        [7, 9],
                        [9, 10],
                        [7, 11],
                        [11, 12],
                        [7, 13],
                        [13, 14],
                        [7, 15],
                        [15, 16],
                        [17, 18],
                        [17, 19],
                        [19, 20],
                        [17, 21],
                        [21, 22],
                        [17, 23],
                        [23, 24],
                        [17, 25],
                        [25, 26],
                    ]
            edge_importance_weighting: true

    decoder:
        type: fc
        params:
            dropout_ratio: 0.05

optim:
    loss: "CrossEntropyLoss"
    optimizer:
        name: Adam
        params:
            lr: 1e-3

    scheduler:
        name: CosineAnnealingLR
        params:
            last_epoch: -1
            T_max: 10

trainer:
    gpus: 1
    max_epochs: 1000

exp_manager:
    create_tensorboard_logger: true
    create_wandb_logger: true
    wandb_logger_kwargs:
        name: "manideepladi"
        project: "Bhosphorus22k"

    create_checkpoint_callback: true
    checkpoint_callback_params:
        monitor: "val_acc"
        mode: "max"
        save_top_k: 3
        dirpath: "experiments/bhosphrous/lstm/"

    early_stopping_callback: true
    early_stopping_params:
        monitor: "val_acc"
        patience: 100
        verbose: true
        mode: "max"
