params:
  train_dataset:
    root_dir: /home/gokulnc/data-disk/datasets/SSL/HDF5/
    file_format: h5
    mask_type: random_spans
    mask_ratio: 0.0
    deterministic_masks: false
    num_channels: 2
    max_frames: 120
    subsampling_method: random
    transforms:
      - PoseSelect:
          preset: mediapipe_holistic_top_body_59
      # - CenterAndScaleNormalize:
      #     reference_points_preset: shoulder_mediapipe_holistic_top_body_59
      # - ShearTransform:
      #     shear_std: 0.1
      # - RotatationTransform:
      #     rotation_std: 0.1
      - AddClsToken:
  
  val_dataset:
    root_dir: /home/gokulnc/data-disk/datasets/Indian/INCLUDE/Pose_Signs/
    file_format: pkl
    mask_type: random_spans
    mask_ratio: 0.0
    deterministic_masks: true
    num_channels: 2
    max_frames: 120
    subsampling_method: uniform
    transforms:
      - PoseSelect:
          preset: mediapipe_holistic_top_body_59
      # - CenterAndScaleNormalize:
      #     reference_points_preset: shoulder_mediapipe_holistic_top_body_59
      - AddClsToken:
  
  lr: 4e-4
  max_epochs: 2000
  batch_size: 64
  num_workers: 6
  val_sanity_checks: 0
  output_path: "model-outputs"

  input_dim: 118
  max_seq_len: 121

model:
  type: bert
  config:
    vocab_size: 32
    hidden_size: 192
    num_hidden_layers: 6
    num_attention_heads: 6
    intermediate_size: 256
    hidden_act: 'gelu'
    hidden_dropout: 0.1
    activation_dropout: 0.1
    attention_dropout: 0.1
    feat_proj_dropout: 0.1
    feat_quantizer_dropout: 0.0
    final_dropout: 0.1
    layerdrop: 0.1
    initializer_range: 0.02
    layer_norm_eps: 1e-05
    feat_extract_norm: 'group'
    feat_extract_activation: 'gelu'
    conv_dim: [256]
    conv_stride: [118]
    conv_kernel: [118]
    conv_bias: False
    num_conv_pos_embeddings: 121
    num_conv_pos_embedding_groups: 16
    do_stable_layer_norm: False
    apply_spec_augment: True
    mask_time_prob: 0.1
    mask_time_length: 5
    mask_feature_prob: 0.0
    mask_feature_length: 10
    num_codevectors_per_group: 320
    num_codevector_groups: 2
    contrastive_logits_temperature: 0.1
    num_negatives: 100
    codevector_dim: 256
    proj_codevector_dim: 256
    diversity_loss_weight: 0.1
    ctc_loss_reduction: 'sum'
    ctc_zero_infinity: False
    gradient_checkpointing: False
    pad_token_id: 0
    bos_token_id: 1
    eos_token_id: 2
