params:
  train_dataset:
    root_dir: /home/gokulnc/data-disk/datasets/SSL/
    file_format: h5
    mask_type: random_spans
    mask_ratio: 0.4
    deterministic_masks: false
    num_channels: 2
    max_frames: 120
    subsampling_method: random
    transforms:
      - PoseSelect:
          preset: mediapipe_holistic_top_body_59
      # - CenterAndScaleNormalize:
      #     reference_points_preset: shoulder_mediapipe_holistic_top_body_59
      # - ShearTransform:
      #     shear_std: 0.1
      # - RotatationTransform:
      #     rotation_std: 0.1
      - AddClsToken:
  
  val_dataset:
    root_dir: /home/gokulnc/data-disk/datasets/Indian/INCLUDE/Pose_Signs/
    file_format: pkl
    mask_type: random_spans
    mask_ratio: 0.4
    deterministic_masks: true
    num_channels: 2
    max_frames: 120
    subsampling_method: uniform
    transforms:
      - PoseSelect:
          preset: mediapipe_holistic_top_body_59
      # - CenterAndScaleNormalize:
      #     reference_points_preset: shoulder_mediapipe_holistic_top_body_59
      - AddClsToken:
  
  lr: 5e-4
  max_epochs: 2000
  batch_size: 128
  num_workers: 6
  val_sanity_checks: 0
  output_path: "model-outputs"

  input_dim: 118
  reg_loss_weight: 1
  use_direction: false
  dir_loss_weight: 1
  d_out_classes: 236

model:
  type: bert
  config:
    hidden_size: 96
    max_position_embeddings: 121
    num_hidden_layers: 6
    num_attention_heads: 6
    intermediate_size: 192
    hidden_act: "gelu"
    hidden_dropout_prob: 0.1
    attention_probs_dropout_prob: 0.1
