params:
  train_data_dir: /home/gokulnc/data-disk/datasets/SSL/corrected_pose_no_sub_one_min_splits
  train_transforms:
    - PoseTemporalSubsample:
        num_frames: 120
    - PoseSelect:
        preset: mediapipe_holistic_top_body_59
    - CenterAndScaleNormalize:
        reference_points_preset: shoulder_mediapipe_holistic_top_body_59
    - ShearTransform:
        shear_std: 0.1
    - RotatationTransform:
        rotation_std: 0.1
  
  val_data_dir: /home/gokulnc/data-disk/datasets/Indian/INCLUDE/Pose_Signs/
  valid_transforms:
    - PoseUniformSubsampling:
        num_frames: 120
    - PoseSelect:
        preset: mediapipe_holistic_top_body_59
    - CenterAndScaleNormalize:
        reference_points_preset: shoulder_mediapipe_holistic_top_body_59
  
  lr: 2e-4
  max_epochs: 2000
  batch_size: 64
  num_workers: 0
  val_sanity_checks: 0
  output_path: "model-outputs"

  input_dim: 118
  reg_loss_weight: 1
  use_direction: true
  dir_loss_weight: 1
  d_out_classes: 236

model_cfg:
  hidden_size: 96
  max_position_embeddings: 121
  num_hidden_layers: 6
  num_attention_heads: 6
  intermediate_size: 192
  hidden_act: "gelu"
  hidden_dropout_prob: 0.1
  attention_probs_dropout_prob: 0.1
