data:
    modality: "pose"
    train_pipeline:
        dataset:
            _target_: slr.datasets.isolated.INCLUDEDataset
            split_file: "/home/gokulnc/data-disk/datasets/Indian/INCLUDE/Train_Test_Split/train_include50.csv"
            root_dir: "/home/gokulnc/data-disk/datasets/Indian/INCLUDE/Pose_Signs"
            modality: "pose"
            splits: "train"

        transforms:
            - PoseSelect:
                preset: mediapipe_holistic_minimal_27
            - VideoDimensionsNormalize:
            - CenterAndScaleNormalize:
                  point_indexes_to_use: [3, 4]
            - ShearTransform:
                  shear_std: 0.1
            - RotatationTransform:
                  rotation_std: 0.1

        dataloader:
            _target_: torch.utils.data.DataLoader
            batch_size: 32
            shuffle: true
            num_workers: 0
            pin_memory: true
            drop_last: false

    valid_pipeline:
        dataset:
            _target_: slr.datasets.isolated.INCLUDEDataset
            split_file: "/home/gokulnc/data-disk/datasets/Indian/INCLUDE/Train_Test_Split/test_include50.csv"
            root_dir: "/home/gokulnc/data-disk/datasets/Indian/INCLUDE/Pose_Signs"
            modality: "pose"
            splits: "test"

        transforms:
            - PoseSelect:
                preset: mediapipe_holistic_minimal_27
            - VideoDimensionsNormalize:
            - CenterAndScaleNormalize:
                  point_indexes_to_use: [3, 4]

        dataloader:
            _target_: torch.utils.data.DataLoader
            batch_size: 32
            shuffle: false
            num_workers: 0
            pin_memory: true
            drop_last: false

model:
    encoder:
        type: gcn
        params:
            num_points: 27
            inward_edges:
                    [
                        [2, 0],
                        [1, 0],
                        [0, 3],
                        [0, 4],
                        [3, 5],
                        [4, 6],
                        [5, 7],
                        [6, 17],
                        [7, 8],
                        [7, 9],
                        [9, 10],
                        [7, 11],
                        [11, 12],
                        [7, 13],
                        [13, 14],
                        [7, 15],
                        [15, 16],
                        [17, 18],
                        [17, 19],
                        [19, 20],
                        [17, 21],
                        [21, 22],
                        [17, 23],
                        [23, 24],
                        [17, 25],
                        [25, 26],
                    ]
                    
    decoder:
        type: bert
        params:
            max_position_embeddings: 256
            layer_norm_eps: 1e-12
            hidden_dropout_prob: 0.1
            hidden_size: 128
            num_attention_heads: 8
            num_hidden_layers: 5
            cls_token: true
            pooling_type: "cls"

optim:
    loss: "CrossEntropyLoss"
    optimizer:
        name: Adam
        params:
            lr: 1e-3

    scheduler:
        name: CosineAnnealingLR
        params:
            last_epoch: -1
            T_max: 10

trainer:
    gpus: 1
    max_epochs: 1000

exp_manager:
    create_tensorboard_logger: true
    create_wandb_logger: false
    wandb_logger_kwargs:
        name: null
        project: null

    create_checkpoint_callback: true
    checkpoint_callback_params:
        monitor: "val_acc"
        mode: "max"
        save_top_k: 3

    early_stopping_callback: true
    early_stopping_params:
        monitor: "val_acc"
        patience: 75
        verbose: true
        mode: "max"
