data:
    modality: "pose"
    train_pipeline:
        dataset:
            _target_: openhands.datasets.isolated.INCLUDEDataset
            split_file: "/home/gokulnc/data-disk/datasets/Indian/INCLUDE/Train_Test_Split/train_include.csv"
            root_dir: "/home/gokulnc/data-disk/datasets/Indian/INCLUDE/Pose_Signs"
            splits: "train"
            modality: "pose"

        transforms:
            - PoseSelect:
                preset: mediapipe_holistic_minimal_27
            # - PoseSelect:
            #       pose_indexes:
            #           [
            #               0,
            #               2,
            #               5,
            #               11,
            #               12,
            #               13,
            #               14,
            #               33,
            #               37,
            #               38,
            #               41,
            #               42,
            #               45,
            #               46,
            #               49,
            #               50,
            #               53,
            #               54,
            #               58,
            #               59,
            #               62,
            #               63,
            #               66,
            #               67,
            #               70,
            #               71,
            #               74,
            #           ]
            # - PoseTemporalSubsample:
            #       num_frames: 32
            - CenterAndScaleNormalize:
                point_indexes_to_use: [3, 4]
                scale_factor: 1
            - ShearTransform:
                shear_std: 0.1
            - RotatationTransform:
                rotation_std: 0.1
            # - ScaleTransform:
            #     scale_std: 0.2

        dataloader:
            _target_: torch.utils.data.DataLoader
            batch_size: 16
            shuffle: true
            num_workers: 1
            pin_memory: true
            drop_last: true

    valid_pipeline:
        dataset:
            _target_: openhands.datasets.isolated.INCLUDEDataset
            split_file: "/home/gokulnc/data-disk/datasets/Indian/INCLUDE/Train_Test_Split/test_include.csv"
            root_dir: "/home/gokulnc/data-disk/datasets/Indian/INCLUDE/Pose_Signs"
            splits: "test"
            modality: "pose"

        transforms:
            - PoseSelect:
                preset: mediapipe_holistic_minimal_27
            # - PoseSelect:
            #       pose_indexes:
            #           [
            #               0,
            #               2,
            #               5,
            #               11,
            #               12,
            #               13,
            #               14,
            #               33,
            #               37,
            #               38,
            #               41,
            #               42,
            #               45,
            #               46,
            #               49,
            #               50,
            #               53,
            #               54,
            #               58,
            #               59,
            #               62,
            #               63,
            #               66,
            #               67,
            #               70,
            #               71,
            #               74,
            #           ]
            # - PoseTemporalSubsample:
            #       num_frames: 32
            - CenterAndScaleNormalize:
                point_indexes_to_use: [3, 4]
                scale_factor: 1

        dataloader:
            _target_: torch.utils.data.DataLoader
            batch_size: 32
            shuffle: false
            num_workers: 8
            pin_memory: true
            drop_last: false

model:
    encoder:
        type: pose-flattener
        params:
            num_points: 27
    decoder:
        type: rnn
        params:
            rnn_type: LSTM
            hidden_size: 128
            num_layers: 4
            bidirectional: true
            use_attention: true

optim:
    loss: 'CrossEntropyLoss'
    optimizer:
        name: Adam
        params:
            lr: 5e-3

    scheduler:
        name: CosineAnnealingLR
        params:
            last_epoch: -1
            T_max: 10

trainer:
    gpus: 1
    max_epochs: 00
    # resume_from_checkpoint: "/home/gokulnc/SLR/outputs/2021-06-30/17-55-58/LSTM-INCLUDE/0/checkpoints/epoch=971-step=45683.ckpt"

exp_manager:
    create_tensorboard_logger: true
    create_wandb_logger: false
    wandb_logger_kwargs:
        name: null
        project: null

    create_checkpoint_callback: true
    checkpoint_callback_params:
        monitor: "val_acc"
        mode: "max"
        save_top_k: 3

    early_stopping_callback: true
    early_stopping_params:
        monitor: "val_acc"
        patience: 100
        verbose: true
        mode: "max"
