data:
    modality: "pose"
    train_pipeline:
        dataset:
            _target_: openhands.datasets.isolated.INCLUDEDataset
            split_file: "/home/gokulnc/data-disk/datasets/Indian/INCLUDE/Train_Test_Split/train_include.csv"
            root_dir: "/home/gokulnc/data-disk/datasets/Indian/INCLUDE/Pose_Signs"
            splits: "train"
            modality: "pose"

        transforms:
            - PoseUniformSubsampling:
                num_frames: 120
            - PoseSelect:
                preset: mediapipe_holistic_top_body_59
            - CenterAndScaleNormalize:
                reference_points_preset: shoulder_mediapipe_holistic_top_body_59
            - AddClsToken:

        dataloader:
            _target_: torch.utils.data.DataLoader
            batch_size: 64
            shuffle: true
            num_workers: 6
            pin_memory: true
            # drop_last: true

    valid_pipeline:
        dataset:
            _target_: openhands.datasets.isolated.INCLUDEDataset
            split_file: "/home/gokulnc/data-disk/datasets/Indian/INCLUDE/Train_Test_Split/test_include.csv"
            root_dir: "/home/gokulnc/data-disk/datasets/Indian/INCLUDE/Pose_Signs"
            splits: "test"
            modality: "pose"

        transforms:
            - PoseUniformSubsampling:
                num_frames: 120
            - PoseSelect:
                preset: mediapipe_holistic_top_body_59
            - CenterAndScaleNormalize:
                reference_points_preset: shoulder_mediapipe_holistic_top_body_59
            - AddClsToken:

        dataloader:
            _target_: torch.utils.data.DataLoader
            batch_size: 32
            shuffle: false
            num_workers: 8
            pin_memory: true
            drop_last: false

model:
    encoder:
        type: pretrained_wav2vec2
        params:
            cfg_file: /home/gokulnc/openhands/examples/ssl/pretrain_wav2vec2.yaml
            ckpt: /home/gokulnc/openhands/outputs/2021-08-04/18-12-33/model-outputs/epoch=577-step=714407.ckpt
    decoder:
        type: fine_tuner
        params:
            pooling_type: cls

optim:
    loss: 'CrossEntropyLoss'
    optimizer:
        name: Adam
        params:
            lr: 1e-4

    scheduler:
        name: CosineAnnealingLR
        params:
            last_epoch: -1
            T_max: 20

trainer:
    gpus: 1
    max_epochs: 3000
    # resume_from_checkpoint: /home/gokulnc/openhands/openhands_experiments/INCLUDE/BERT-Fine-tuned-full/epoch=1493-step=82169.ckpt

exp_manager:
    create_tensorboard_logger: true
    create_wandb_logger: false
    wandb_logger_kwargs:
        name: null
        project: null

    create_checkpoint_callback: true
    checkpoint_callback_params:
        monitor: "val_acc"
        mode: "max"
        save_top_k: 3

    early_stopping_callback: true
    early_stopping_params:
        monitor: "val_acc"
        patience: 100
        verbose: true
        mode: "max"
